config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :omniauth_callbacks =>  "users/omniauth_callbacks"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "items#index"
  get   'users/:id'   =>  'users#show'
  get   'items/new'   =>  'items#new' 
  get 'items/:id/check', to: 'items#check', as: :logout 
  delete 'items/:id', to: 'items#destroy', as: :destroy

  resource :items do
    collection do
      get 'get_category_children'
      get 'get_category_grandchildren'
      get 'get_brand'
    end
end
get 'items/:id'=> 'items#detail'
  
  resources :users, only: [:edit, :update]

  resources :mypages do
    collection do
      get 'card'
      get 'identification'
      get 'logout'
    end
  end

  resources :signup do
    collection do
      get 'step1'
      get 'step2'
      get 'step3'
      get 'step4'
      get 'done'
    end
  end

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :searches,only:[:index] do
    collection do
      get 'detail_search'
    end
  end
  
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  belongs_to :saler, class_name: "User", foreign_key: :saler_id, optional: true
  belongs_to :buyer, class_name: "User", foreign_key: :buyer_id, optional: true
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images
  validates :price, numericality: { only_integer: true, greater_than: 300, less_than: 9999999}
  validates :name, presence: true, length: { maximum: 26 }
  validates :status, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  validates :category_id, presence: true
  validates :condition, presence: true
  validates :burden, presence: true
  validates :region, presence: true
  validates :sending_days, presence: true


  def self.search(search)
    return Item.all unless search
    Item.where(['name LIKE ?', "%#{search}%"])
  end

  enum condition:{
    新品、未使用: 1, 
    未使用に近い: 2, 
    目立った傷や汚れなし: 3, 
    やや傷や汚れあり: 4, 
    傷や汚れあり: 5, 
    全体的に状態が悪い: 6
  }

  enum burden:{
    送料込み（出品者負担）:1,
    着払い（購入者負担）:2
  }


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :move_to_login, only: [:new, :check, :detail]
  before_action :set_item, only: [:destroy]

  def index
    @item = Item.new
    @items = Item.all
    @ladies = Category.find(1)
    @ladies_grandchild = @ladies.indirects
    @men = Category.find(219)
    @men_grandchild = @men.indirects
  end

  def get_category_children
    @category_children = Category.find_by(id: "#{params[:id]}", ancestry: nil).children
    respond_to do |format|
      format.html
      format.json
    end
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find("#{params[:id]}").children
    @items = Item.all
    respond_to do |format|
      format.html
      format.json
    end
  end

  def get_brand
    @fashion1 = Category.where(id: 1..71)
    @fashion2 = Category.where(id:184..202)
    @fashion3 = Category.where(id:205..211)
    @fashion4 = Category.where(id:219..269)
    @fashion5 = Category.where(id:378..457)
    respond_to do |format|
      format.html
      format.json
    end
  end
  
  def detail
    @items = Item.all
    @item = Item.find(params[:id])
    @category = Category.find(@item.category_id)
    @categoryparent = @category.parent
    @categorygrandparent = @categoryparent.parent

  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render '/items/new'
    end
  end

  
  def new
      @item = Item.new
      @item.images.build
      @category_parent = ["---"]
      @category_parent = Category.where(ancestry: nil).pluck(:name)
      @category_parent.unshift("---")
  end

  def destroy
    if @item.saler_id == current_user.id
      if @item.destroy
        redirect_to root_path
      else
        render '/items/#{params[:id]}'
      end
    end
  end

  def check
    @items = Item.all
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :status, :body,:category_id, :size, :brandname, :condition,:burden,:region,:sending_days,:price, images_attributes: [:image]).merge(saler_id: current_user.id, buyer_id: current_user.id)
  end
  
  def move_to_login
    redirect_to new_user_session_path unless user_signed_in?
  end

  def set_item
    @item = Item.find(params[:id])
  end

  
  end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_bottom.html.haml
.main__bottom__center
  .main__bottom__center__left
    .main__bottom__center__left__head スマホでかんたんフリマアプリ
    .main__bottom__center__left__heading 今すぐ無料ダウンロード！
    .main__bottom__center__left__box
      .main__bottom__center__left__box__mercari
        = image_tag  "logo_red.svg"
      .main__bottom__center__left__box__apple
        =link_to "#" do
          = image_tag  "https://i0.wp.com/iphone-media.net/wp-content/uploads/2016/11/duellinks03.png?fit=564%2C168",class:"main__bottom__center__left__box__apple__size"
      .main__bottom__center__left__box__google
        =link_to "#" do
          =image_tag  "https://img.tsite.jp/r/app/img/download-google.gif",class:"main__bottom__center__left__box__google__size"
    
  .main__bottom__center__right
    =image_tag  "https://cdn.pixabay.com/photo/2014/10/23/20/51/iphone-500291__480.jpg",class:"main__bottom__center__right__size"

app/views/items/_footer.html.haml
.main__footer__contents
  .main__footer__contents__about
    %h2.main__footer__contents__about__title メルカリについて
    .main__footer__contents__about__title__class
      %ul.main__footer__contents__about__title__class
        %li.main__footer__contents__about__title__class__name 
          =link_to "#",class:"main__footer__contents__about__title__class__name__tag" do
            会社概要（運営会社）
        %li.main__footer__contents__about__title__class__name
          =link_to "#",class:"main__footer__contents__about__title__class__name__tag" do
            採用情報
        %li.main__footer__contents__about__title__class__name
          =link_to "#",class:"main__footer__contents__about__title__class__name__tag" do
            プレスリリース
        %li.main__footer__contents__about__title__class__name 
          =link_to "#",class:"main__footer__contents__about__title__class__name__tag" do
            公式ブログ
        %li.main__footer__contents__about__title__class__name
          =link_to "#",class:"main__footer__contents__about__title__class__name__tag" do
            メルカリロゴ利用ガイドライン
        .main__footer__contents__about__title__class__name__icon
          =link_to "https://twitter.com/", class: "main__footer__contents__about__title__class__name__icon__twitter" do
            = icon('fab', 'twitter', class: "main__footer__contents__about__title__class__name__icon__twitter__box")
          =link_to "https://www.facebook.com/", class: "main__footer__contents__about__title__class__name__icon__facebook" do
            = icon('fab', 'facebook-square',  class: "main__footer__contents__about__title__class__name__icon__facebook__box")

  .main__footer__contents__guide
    %h2.main__footer__contents__guide__title ヘルプ＆ガイド
    .main__footer__contents__guide__title__class
      %ul.main__footer__contents__guide__title__class
        %li.main__footer__contents__guide__title__class__name
          =link_to "#",class:"main__footer__contents__guide__title__class__name__tag" do
            メルカリガイド
        %li.main__footer__contents__guide__title__class__name
          =link_to "#",class:"main__footer__contents__guide__title__class__name__tag" do
            らくらくメルカリ便
        %li.main__footer__contents__guide__title__class__name
          =link_to "#",class:"main__footer__contents__guide__title__class__name__tag" do
            ゆうゆうメルカリ便
        %li.main__footer__contents__guide__title__class__name
          =link_to "#",class:"main__footer__contents__guide__title__class__name__tag" do
            大型メルカリ便
        %li.main__footer__contents__guide__title__class__name
          =link_to "#",class:"main__footer__contents__guide__title__class__name__tag" do
            車体取引ガイド
        %li.main__footer__contents__guide__title__class__name
          =link_to "#",class:"main__footer__contents__guide__title__class__name__tag" do
            メルカリあんしん・あんぜん宣言！
        %li.main__footer__contents__guide__title__class__name
          =link_to "#",class:"main__footer__contents__guide__title__class__name__tag" do
            偽ブランド品撲滅への取り組み
        %li.main__footer__contents__guide__title__class__name
          =link_to "#",class:"main__footer__contents__guide__title__class__name__tag" do
            メルカリボックス

  .main__footer__contents__privace
    %h2.main__footer__contents__privace__title プライバシーと利用規約
    .main__footer__contents__privace__title__box
      .main__footer__contents__privace__title__box__class
        %ul.main__footer__contents__privace__title__box__class
          %li.main__footer__contents__privace__title__box__class__name
            =link_to "#",class:"main__footer__contents__privace__title__box__class__name__tag" do
              プライバシーポリシー
          %li.main__footer__contents__privace__title__box__class__name
            =link_to "#",class:"main__footer__contents__privace__title__box__class__name__tag" do
              メルカリ利用規約
          %li.main__footer__contents__privace__title__box__class__name
            =link_to "#",class:"main__footer__contents__privace__title__box__class__name__tag" do
              あんしんスマホサポート制度に関する利用規約
          %li.main__footer__contents__privace__title__box__class__name
            =link_to "#",class:"main__footer__contents__privace__title__box__class__name__tag" do
              コンプライアンスポリシー
      .main__footer__contents__privace__title__box__place
        %ul.main__footer__contents__privace__title__box__place
          %li.main__footer__contents__privace__title__box__place__name
            =link_to "#",class:"main__footer__contents__privace__title__box__place__name__tag" do
              個人データの安全管理に係る基本方針
          %li.main__footer__contents__privace__title__box__place__name
            =link_to "#",class:"main__footer__contents__privace__title__box__place__name__tag" do
              特定商取引に関する表記
          %li.main__footer__contents__privace__title__box__place__name
            =link_to "#",class:"main__footer__contents__privace__title__box__place__name__tag" do
              資金決済法に基づく表示
          %li.main__footer__contents__privace__title__box__place__name
            =link_to "#",class:"main__footer__contents__privace__title__box__place__name__tag" do
              法令順守と犯罪抑止のために

  .main__footer__contents__country
    %h2.main__footer__contents__country__title 国
    .main__footer__contents__country__title__class
      %ul.main__footer__contents__country__title__class
        %li.main__footer__contents__country__title__class__name
          =link_to"#",class:"main__footer__contents__country__title__class__name__tag" do
            日本
        %li.main__footer__contents__country__title__class__name
          =link_to"#",class:"main__footer__contents__country__title__class__name__tag" do
            United States

.main__footer__logo
  .main__footer__logo__box
    .main__footer__logo__box__logo 
      =link_to "#" do
        = image_tag  "fmarket_logo_white.svg"
    .main__footer__logo__box__color ©️ 2019 Mercari

app/views/items/_header.html.haml
.headerBox
  .headerBox__main
    .headerBox__main__search
      .headerBox__main__search__logo
        =link_to "..",class:"headerBox__main__search__logo__link" do
          = image_tag  "fmarket_logo_red.svg",class:"headerBox__main__search__logo__link__box"
      .headerBox__main__search__input
        .headerBox__main__search__input__box
          = form_tag(searches_path,method: :get) do
            %label
              = text_field_tag :search, "",placeholder:"何かお探しですか？",class: "search-box"
              %i.fas.fa-search{class: "search-icon"}
              = submit_tag 'search', :name => nil
    .headerBox__main__bottom
      .headerBox__main__bottom__select
        .headerBox__main__bottom__select__category
          .headerBox__main__bottom__select__category__categorySearch
            = image_tag('category.png',width:'30',height:'25')
          .headerBox__main__bottom__select__category__categorySearch__list__a カテゴリーから探す
        .headerBox__main__bottom__select__brand 
          .headerBox__main__bottom__select__brand__brandSearch
            = image_tag('brand.png',width:'30',height:'25')
          .headerBox__main__bottom__select__brand__brandSearch__list__b  ブランドから探す
      
      
      .headerBox__main__bottom__member
        -if user_signed_in?
          .headerBox__main__bottom__member__check
            =link_to "#" ,class:"header-linkto" do
              = icon('far', 'heart', class: "header-check-size")
              いいね！一覧
          .headerBox__main__bottom__member__check
            =link_to "#" ,class:"header-linkto" do
              = icon('far', 'bell', class: "header-check-size")
              お知らせ
          .headerBox__main__bottom__member__check
            =link_to "#" ,class:"header-linkto" do
              = icon('fas', 'check', class: "header-check-size")
              やることリスト
          .headerBox__main__bottom__member__mypage
            =link_to "/mypages" ,class:"header-linkto" do
              = icon('fas', 'user-circle', class: "header-icon-size")
              マイページ
  
        -else
          .headerBox__main__bottom__member__new
            =link_to signup_index_path ,class:"headerBox__main__bottom__member__new__letter" do
              新規会員登録
          .headerBox__main__bottom__member__login
            =link_to new_user_session_path ,class:"headerBox__main__bottom__member__login__moji" do
              ログイン

app/views/items/_itemlist.html.haml
.main__item__header
  .main__item__header__heading 人気のカテゴリー
  .main__item__header__list
    .main__item__header__list__women 
      .main__item__header__list__women__box
        =link_to "#women__id" ,class:"main__item__header__list__women__box__tag" do
          レディース
    .main__item__header__list__men 
      .main__item__header__list__men__box
        =link_to "#men__id" ,class:"main__item__header__list__men__box__tag" do
          メンズ
.main__item__box
  .main__item__box__list
    .main__item__box__list__women
      .main__item__box__list__women__header
        .main__item__box__list__women__header__title
          #women__id
            レディース新着アイテム
        .main__item__box__list__women__header__details 
          =link_to "#", class:"main__item__box__list__women__header__details__tag" do
            もっとみる ＞
      %ul.main__item__box__list__women__item
        - @items.order('created_at DESC').each do |item|
          -@ladies_grandchild.each do |lady|
            - if item.category_id == lady.id
              %li.main__item__box__list__women__item__box
                .main__item__box__list__women__item__box__in
                  =link_to "/items/#{item.id}" ,class:"main__item__box__list__women__item__box__tag" do
                    .main__item__box__list__women__item__box__image
                      = image_tag item.images[0].image_url,{width:'100%' , height:'100%'}
                      .main__item__box__list__women__item__box__image__place            
                        .main__item__box__list__women__item__box__image__place__language
                          ¥#{item.price.to_s(:delimited)}
                    .main__item__box__list__women__item__box__text
                      .main__item__box__list__women__item__box__text__language
                        = item.name

    .main__item__box__list__women
      .main__item__box__list__women__header
        .main__item__box__list__women__header__title
          #men__id
            メンズ新着アイテム
        .main__item__box__list__women__header__details
          =link_to "#" , class:"main__item__box__list__women__header__details__tagtag" do
            もっとみる ＞
      %ul.main__item__box__list__women__item
        - @items.order('created_at DESC').each do |item|
          -@men_grandchild.each do |men|
            - if item.category_id == men.id
              %li.main__item__box__list__women__item__box
                .main__item__box__list__women__item__box__in
                  =link_to "/items/#{item.id}" ,class:"main__item__box__list__women__item__box__tag" do
                    .main__item__box__list__women__item__box__image
                      = image_tag item.images[0].image_url,{width:'100%' , height:'100%'}
                      .main__item__box__list__women__item__box__image__place            
                        .main__item__box__list__women__item__box__image__place__language
                          ¥#{item.price.to_s(:delimited)}
                    .main__item__box__list__women__item__box__text
                      .main__item__box__list__women__item__box__text__language
                        = item.name


.main__item__header
  .main__item__header__heading 人気のブランド
  .main__item__header__list
    .main__item__header__list__women 
      .main__item__header__list__women__box
        =link_to "#syanel__id" ,class:"main__item__header__list__women__box__tag" do
          シャネル
    .main__item__header__list__men 
      .main__item__header__list__men__box
        =link_to "#naiki__id" ,class:"main__item__header__list__men__box__tag" do
          ナイキ
.main__item__box
  .main__item__box__list
    .main__item__box__list__women
      .main__item__box__list__women__header
        .main__item__box__list__women__header__title
          #syanel__id
            シャネル新着アイテム
        .main__item__box__list__women__header__details 
          =link_to "#" , class:"main__item__box__list__women__header__details__tag" do
            もっとみる ＞
      %ul.main__item__box__list__women__item
        - @items.order('created_at DESC').each do |item|
          - if item.brandname == "シャネル"
            %li.main__item__box__list__women__item__box
              .main__item__box__list__women__item__box__in
                =link_to "/items/#{item.id}" ,class:"main__item__box__list__women__item__box__tag" do
                  .main__item__box__list__women__item__box__image
                    = image_tag item.images[0].image_url,{width:'100%' , height:'100%'}
                    .main__item__box__list__women__item__box__image__place            
                      .main__item__box__list__women__item__box__image__place__language
                        ¥#{item.price.to_s(:delimited)}
                  .main__item__box__list__women__item__box__text
                    .main__item__box__list__women__item__box__text__language
                      = item.name

    .main__item__box__list__women
      .main__item__box__list__women__header
        .main__item__box__list__women__header__title
          #naiki__id
            ナイキ新着アイテム
        .main__item__box__list__women__header__details
          =link_to "#" , class:"main__item__box__list__women__header__details__tagtag" do
            もっとみる ＞
      %ul.main__item__box__list__women__item
        - @items.order('created_at DESC').each do |item|
          - if item.brandname == "ナイキ"
            %li.main__item__box__list__women__item__box
              .main__item__box__list__women__item__box__in
                =link_to "/items/#{item.id}" ,class:"main__item__box__list__women__item__box__tag" do
                  .main__item__box__list__women__item__box__image
                    = image_tag item.images[0].image_url,{width:'100%' , height:'100%'}
                    .main__item__box__list__women__item__box__image__place            
                      .main__item__box__list__women__item__box__image__place__language
                        ¥#{item.price.to_s(:delimited)}
                  .main__item__box__list__women__item__box__text
                    .main__item__box__list__women__item__box__text__language
                      = item.name

app/views/items/_slideshow.html.haml
.slideshow-slides
  = link_to image_tag('noname.png',width:'106%'),'./', class:'slide'
  = link_to image_tag('camping.png',width:'106%'),'./', class:'slide'
  = link_to image_tag('apri.png',width:'106%'),'./', class:'slide'
.slideshow-nav
  = link_to './', class: 'prev' do
    %li.fa.fa-angle-left.fa-3x.fa-right
  = link_to './', class: 'next' do
    %li.fa.fa-angle-right.fa-3x.fa-left
.slideshow-indicator
  = link_to 

app/views/items/detail.html.haml
.main_flame
  .header
    = render "header"
  .main__item__boxs
    .detail__main
      .detail__main__box
        .detail__main__box__flame
          %h3.detail__main__box__flame__title 
            =@item.name
          .detail__main__box__flame__content
            .detail__main__box__flame__content__sub
              .detail__main__box__flame__content__sub__itemphoto
                .detail__main__box__flame__content__sub__itemphoto__mainphoto
                  = image_tag @item.images[0].image_url, class:'detail__main__box__flame__content__sub__itemphoto__mainphoto__size'
                  //= image_tag @item.images[0].image,size: "180x300"
                  //= link_to image_tag('jeans.jpg',width:'180', height:'300')     
                .detail__main__box__flame__content__sub__itemphoto__subphoto
                  - if @item.images[0].present?
                    .detail__main__box__flame__content__sub__itemphoto__subphoto__box
                      = image_tag @item.images[0].image_url, class:'detail__main__box__flame__content__sub__itemphoto__subphoto__box__size'
                  - if @item.images[1].present?
                    .detail__main__box__flame__content__sub__itemphoto__subphoto__box
                      = image_tag @item.images[1].image_url, class:'detail__main__box__flame__content__sub__itemphoto__subphoto__box__size'
                  - if @item.images[2].present?
                    .detail__main__box__flame__content__sub__itemphoto__subphoto__box
                      = image_tag @item.images[2].image_url, class:'detail__main__box__flame__content__sub__itemphoto__subphoto__box__size'             
              .detail__main__box__flame__content__sub__table
                %table.tbody{border:"1"}
                  %tr
                    %th 出品者
                    %td
                      = link_to '#' do
                        =@item.saler.nickname
                      .item-user-rating
                        .item-user-rating__1
                          %i.fas.fa-laugh.laugh
                          %span 160
                        .item-user-rating__2
                          %i.far.fa-meh.normal
                          %span 10
                        .item-user-rating__3
                          %i.far.fa-frown.bad
                          %span 2
                  %tr
                    %th カテゴリー
                    %td
                      = link_to '#' do
                        = @categorygrandparent.name
                      %br
                      = link_to '#' do
                        ＞ #{@categoryparent.name}
                      %br
                      = link_to  '#' do
                        ＞ #{@item.category.name}
                  %tr
                    %th ブランド
                    %td 
                      = link_to '#' do
                        = @item.brandname
                  %tr
                    %th 商品のサイズ
                    %td 
                      = @item.size
                  %tr
                    %th 商品の状態
                    %td
                      = @item.condition
                  %tr
                    %th 配送料の負担
                    %td
                      = @item.burden
                  %tr
                    %th 配送の方法
                    %td ゆうゆうメルカリ便
                  %tr
                    %th 配送元地域
                    %td
                      = @item.region
                  %tr
                    %th 配送日の目安
                    %td
                      = @item.sending_days
            .detail__main__box__flame__content__itemprice
              %span.detail__main__box__flame__content__itemprice__price ¥#{@item.price.to_s(:delimited)}
              %span.detail__main__box__flame__content__itemprice__tax (税込)
              %span.detail__main__box__flame__content__itemprice__shipfree 送料込み
            -unless current_user.id == @item.saler_id
              = link_to logout_path, method: :get,class:'detail__main__box__flame__content__item-buy-btn' do
                購入画面に進む
              .detail__main__box__flame__content__itemdescription
                %p.detail__main__box__flame__content__itemdescription__inner 商品の説明はありません
              .detail__main__box__flame__content__mainitemdescription
                %p.detail__main__box__flame__content__mainitemdescription__inner 
                =@item.body
              .detail__main__box__flame__content__item-btn-container
                .detail__main__box__flame__content__item-btn-container__item-btn-left 
                  %button.detail__main__box__flame__content__item-btn-container__item-btn-left__good
                    %i.fa.fa-heart.heart
                    %span いいね！
                    %span.like-num 2
                  = link_to '#', class:'detail__main__box__flame__content__item-btn-container__item-btn-left__nogood' do
                    %span 不適切な商品の報告
                .detail__main__box__flame__content__item-btn-container__item-btn-right
                  = link_to '#', class:'detail__main__box__flame__content__item-btn-container__item-btn-right__safety' do
                    %i.fa.fa-lock
                    %span あんしん・あんぜんへの取り組み
            - else
              .detail__main__box__flame__content__mainitemdescription
                %p.detail__main__box__flame__content__mainitemdescription__inner 
                =@item.body
              = link_to logout_path, method: :get, class:'detail__main__box__flame__content__item-edit-btn' do
                商品の編集
              %p.detail__main__box__flame__content__itemdescription__text-center or
              = link_to destroy_path, method: :delete, class:'detail__main__box__flame__content__item-delete-btn' do
                この商品を削除する
              .detail__main__box__flame__content__item-btn-container
      .detail__main__message
        .detail__main__message__box
          %p.detail__main__message__box__caution 相手のことを考え丁寧なコメントを心がけましょう。不快にな言葉遣いなどは利用制限や退会処分となることがあります。
          %textarea{type: "text", class: "detail__main__message__box__text"}
          %button{type: "submit", class: "detail__main__message__box__sendbtn"} コメントする
      %ul.detail__main__link
        %li.detail__main__link__left
          =link_to '#',class:'detail__main__link__left__prev' do
            %i.fa.fa-chevron-left.leftarrow
            .detail__main__link__left__prev__detail 
            ベスパ   ヴェスパ   キーホルダー   
            %br イタリア ベスパより購入
        %li.detail__main__link__right
          =link_to '#',class:'detail__main__link__right__next' do
            .detail__main__link__right__next__detail
            静電気除電(1連)トリプルクローバープレス
            %i.fa.fa-chevron-right.rightarrow
      .detail__main__flame
        .detail__main__flame__social-media-box
          .detail__main__flame__social-media-box__text-center
          %ul.detail__main__flame__social-media-box__box
            %li.detail__main__flame__social-media-box__box__facebook
              = link_to '#' do
                %i.fab.fa-facebook-square.facebook
            %li.detail__main__flame__social-media-box__box__twitter
              = link_to '#' do
                %i.fab.fa-twitter-square.twitter
            %li.detail__main__flame__social-media-box__box__pinterest
              = link_to '#' do
                %i.fab.fa-pinterest-square.pinterest
      .detail__main__user-profile
        .detail__main__user-profile__box
          = link_to "#" , class:'detail__main__user-profile__box__link' do
            %p.detail__main__user-profile__box__link__title #{@item.saler.nickname}さんのその他の出品
            %ul.detail__main__user-profile__box__itembox
              - @items.each do |item|
                - if item.saler_id === @item.saler_id
                  %li.detail__main__user-profile__box__itembox__goods
                    .detail__main__user-profile__box__itembox__goods__ind
                      =link_to "/items/#{item.id}", class:'detail__main__user-profile__box__itembox__goods__ind__link' do
                        .detail__main__user-profile__box__itembox__goods__ind__link__imagebox
                          = image_tag item.images[0].image_url, class:'detail__main__user-profile__box__itembox__goods__ind__link__imagebox__image'
                        %p.detail__main__user-profile__box__itembox__goods__ind__link__description
                          = item.name
                        .detail__main__user-profile__box__itembox__goods__ind__link__price ¥#{item.price.to_s(:delimited)}
                        .detail__main__uer-profile__box__itembox__goods__ind__link__rating{style:"text-align:right"}
                          %i.far.fa-heart.heart2
                          %span.detail__main__user-profile__box__itembox__goods__ind__link__rating__value 2
      .detail__main__user-profile
        .detail__main__user-profile__box
          = link_to "#" , class:'detail__main__user-profile__box__link' do
            %p.detail__main__user-profile__box__link__title #{@item.category.name}のその他の出品
            .detail__main__user-profile__box__itembox
              - @items.each do |item|
                - unless item.id === @item.id
                  - if item.category_id === @item.category_id
                    .detail__main__user-profile__box__itembox__goods
                      .detail__main__user-profile__box__itembox__goods__ind
                        =link_to "/items/#{item.id}", class:'detail__main__user-profile__box__itembox__goods__ind__link' do
                          .detail__main__user-profile__box__itembox__goods__ind__link__imagebox
                            =image_tag item.images[0].image_url, class:'detail__main__user-profile__box__itembox__goods__ind__link__imagebox__image'
                          %p.detail__main__user-profile__box__itembox__goods__ind__link__description
                            = item.name
                          .detail__main__user-profile__box__itembox__goods__ind__link__price ¥#{item.price.to_s(:delimited)}
                          .detail__main__uer-profile__box__itembox__goods__ind__link__rating{style:"text-align:right"}
                            %i.far.fa-heart.heart2
                            %span.detail__main__user-profile__box__itembox__goods__ind__link__rating__value 2
      .detail__main__bread-crumbs
        %ul.detail__main__bread-crumbs__list
          %li.detail__main__bread-crumbs__list__catogry1 メルカリ >
          %li.detail__main__bread-crumbs__list__catogry2 ジーンズ（レディース）          
  .main__bottom
    = render "bottom"
  .main__footer
    = render "footer"

app/views/items/index.html.haml
.header
  = render "header"
.body_main
  .slideshow
    = render "slideshow"
.main__item
  = render "itemlist"
.main__saleButton
  = link_to "/items/new" do
    = image_tag "salebutton2.png",class:"sale-size"
.main__bottom
  = render "bottom"
.main__footer
  = render "footer"