config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :omniauth_callbacks =>  "users/omniauth_callbacks"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "items#index"
  get   'users/:id'   =>  'users#show'
  get   'items/new'   =>  'items#new' 
  get 'items/:id/check', to: 'items#check', as: :logout 
  delete 'items/:id', to: 'items#destroy', as: :destroy

  resource :items do
    collection do
      get 'get_category_children'
      get 'get_category_grandchildren'
      get 'get_brand'
    end
end
get 'items/:id'=> 'items#detail'
  
  resources :users, only: [:edit, :update]

  resources :mypages do
    collection do
      get 'card'
      get 'identification'
      get 'logout'
    end
  end

  resources :signup do
    collection do
      get 'step1'
      get 'step2'
      get 'step3'
      get 'step4'
      get 'done'
    end
  end

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :searches,only:[:index] do
    collection do
      get 'detail_search'
    end
  end
  
end

app/models/card.rb
class Card < ApplicationRecord

  belongs_to :user

end

app/controllers/card_controller.rb
class CardController < ApplicationController
  require "payjp"

  def new
    card = Card.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end

  def pay #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      description: '登録テスト', #なくてもOK
      # email: current_user.email, #なくてもOK
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) #念の為metadataにuser_idを入れましたがなくてもOK
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete #PayjpとCardデータベースを削除します
    card = Card.find_by(user_id: current_user.id)
    if card.blank?
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to controller: :mypages, action: :card
  end

  def show #Cardのデータpayjpに送り情報を取り出します
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to controller: :mypages, action: :card 
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end

end

app/helpers/card_helper.rb
module CardHelper
end

app/views/card/new.html.haml
.mypage
  .header
    = render "/items/header"

  .mypage_panbox

  .mypage__main
    .mypage__main__margin
      .mypage__main__margin__left 
        %ul.mypage__main__margin__left__ul
          %li.mypage__main__margin__left__ul__text.a
            = link_to "/mypages" ,class:"mypage-text" do
              マイページ
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              お知らせ
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              やることリスト
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              いいね！一覧
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              出品する
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              出品した商品 - 出品中
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              出品した商品 - 取引中
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              出品した商品 - 売却済み
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              購入した商品 - 取引中
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              購入した商品 - 過去の取引
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              ニュース一覧
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              評価一覧
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              ガイド
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              お問い合わせ
              = icon('fas', 'chevron-right',  class: "right")
        %h3.mypage__main__margin__left__head メルペイ
        %ul.mypage__main__margin__left__ul
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              残高・振込申請
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              ポイント
              = icon('fas', 'chevron-right',  class: "right")
        %h3.mypage__main__margin__left__head 設定
        %ul.mypage__main__margin__left__ul
          %li.mypage__main__margin__left__ul__text.a
            = link_to edit_user_path(current_user) ,class:"mypage-text" do
              プロフィール
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              発生元・お届け先住所変更
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.bold-color
            = link_to card_index_path ,class:"mypage-text" do
              支払い方法
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              メール/パスワード
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "/mypages/identification" ,class:"mypage-text" do
              本人情報
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              電話番号の確認
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "/mypages/logout" ,class:"mypage-text" do
              ログアウト
              = icon('fas', 'chevron-right',  class: "right")


      .mypage__main__margin__right
        .mypage__main__margin__right__credit
          .mypage__main__margin__right__credit__header クレジット情報入力
          .mypage__main__margin__right__credit__regi
            = form_tag(pay_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
              .mypage__main__margin__right__credit__regi__card
                .mypage__main__margin__right__credit__regi__card__number
                  .mypage__main__margin__right__credit__regi__card__number__text
                    .mypage__main__margin__right__credit__regi__card__number__text__text1
                      カード番号
                    .mypage__main__margin__right__credit__regi__card__number__text__text2
                      必須
                  .mypage__main__margin__right__credit__regi__card__number__form
                    = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
                
              
                .mypage__main__margin__right__credit__regi__card__day
                  .mypage__main__margin__right__credit__regi__card__day__text
                    .mypage__main__margin__right__credit__regi__card__day__text1
                      有効期限
                    .mypage__main__margin__right__credit__regi__card__day__text2
                      必須
                  .mypage__main__margin__right__credit__regi__card__day__form
                    .mypage__main__margin__right__credit__regi__card__day__form__month
                      %select#exp_month{name: "exp_month", type: "text",class:"year-box"}
                        %option{value: ""} --
                        %option{value: "1"}01
                        %option{value: "2"}02
                        %option{value: "3"}03
                        %option{value: "4"}04
                        %option{value: "5"}05
                        %option{value: "6"}06
                        %option{value: "7"}07
                        %option{value: "8"}08
                        %option{value: "9"}09
                        %option{value: "10"}10
                        %option{value: "11"}11
                        %option{value: "12"}12
                    .mypage__main__margin__right__credit__regi__card__day__form__monthtext 月
                    .mypage__main__margin__right__credit__regi__card__day__form__year
                      %select#exp_year{name: "exp_year", type: "text"}
                        %option{value: ""} --
                        %option{value: "2019"}19
                        %option{value: "2020"}20
                        %option{value: "2021"}21
                        %option{value: "2022"}22
                        %option{value: "2023"}23
                        %option{value: "2024"}24
                        %option{value: "2025"}25
                        %option{value: "2026"}26
                        %option{value: "2027"}27
                        %option{value: "2028"}28
                        %option{value: "2029"}29
                    .mypage__main__margin__right__credit__regi__card__day__form__yeartext 年
                
              
                .mypage__main__margin__right__credit__regi__card__security
                  .mypage__main__margin__right__credit__regi__card__security__text
                    .mypage__main__margin__right__credit__regi__card__security__text__text1
                      セキュリティコード
                    .mypage__main__margin__right__credit__regi__card__security__text__text2
                      必須
                  .mypage__main__margin__right__credit__regi__card__security__form
                    = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面4桁もしくは3桁の番号", maxlength: "4", id: "cvc"
               
                  .mypage__main__margin__right__credit__regi__card__info
                    = link_to "#" ,class:"question-size" do
                      = icon('fas', 'question-circle',  class: "")
                      カード裏面の番号とは？
               
                .mypage__main__margin__right__credit__regi__card__submit
                #card_token
                  = submit_tag "追加する", id: "token_submit"



  .main__bottom
    = render "/items/bottom"
  .main__footer
    = render "/items/footer"
  .main__saleButton
    = link_to new_items_path do
      = image_tag "salebutton2.png",class:"sale-size"

app/views/card/show.html.haml
.mypage
  .header
    = render "/items/header"

  .mypage_panbox

  .mypage__main
    .mypage__main__margin
      .mypage__main__margin__left 
        %ul.mypage__main__margin__left__ul
          %li.mypage__main__margin__left__ul__text.a
            = link_to "/mypages" ,class:"mypage-text" do
              マイページ
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              お知らせ
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              やることリスト
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              いいね！一覧
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              出品する
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              出品した商品 - 出品中
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              出品した商品 - 取引中
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              出品した商品 - 売却済み
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              購入した商品 - 取引中
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              購入した商品 - 過去の取引
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              ニュース一覧
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              評価一覧
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              ガイド
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              お問い合わせ
              = icon('fas', 'chevron-right',  class: "right")
        %h3.mypage__main__margin__left__head メルペイ
        %ul.mypage__main__margin__left__ul
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              残高・振込申請
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              ポイント
              = icon('fas', 'chevron-right',  class: "right")
        %h3.mypage__main__margin__left__head 設定
        %ul.mypage__main__margin__left__ul
          %li.mypage__main__margin__left__ul__text.a
            = link_to edit_user_path(current_user) ,class:"mypage-text" do
              プロフィール
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              発生元・お届け先住所変更
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.bold-color
            = link_to card_index_path ,class:"mypage-text" do
              支払い方法
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              メール/パスワード
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "/mypages/identification" ,class:"mypage-text" do
              本人情報
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "#" ,class:"mypage-text" do
              電話番号の確認
              = icon('fas', 'chevron-right',  class: "right")
          %li.mypage__main__margin__left__ul__text.a
            = link_to "/mypages/logout" ,class:"mypage-text" do
              ログアウト
              = icon('fas', 'chevron-right',  class: "right")


      .mypage__main__margin__right
        .mypage__main__margin__right__credit
          .mypage__main__margin__right__credit__header 支払い方法
          .mypage__main__margin__right__credit__number
            .mypage__main__margin__right__credit__number__form
              .mypage__main__margin__right__credit__number__form__header
                クレジットカード一覧
              .mypage__main__margin__right__credit__number__form__info.padding-credit
                .mypage__main__margin__right__credit__number__form__info__image
                  = form_tag(delete_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
                    %input{ type: "hidden", name: "card_id", value: "" }
                    %button 削除する
                  = image_tag "logo_visa.gif", class:"visa-size"
                .mypage__main__margin__right__credit__number__form__info__number
                  = "**** **** **** " + @default_card_information.last4
                .mypage__main__margin__right__credit__number__form__info__number
                  - exp_month = @default_card_information.exp_month.to_s
                  - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                  = exp_month + " / " + exp_year
            .mypage__main__margin__right__credit__link
              =link_to "#" ,class:"credit-link" do
                支払い方法について
                = icon('fas', 'chevron-right',  class: "")




  .main__bottom
    = render "/items/bottom"
  .main__footer
    = render "/items/footer"
  .main__saleButton
    = link_to new_items_path do
      = image_tag "salebutton2.png",class:"sale-size"